<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Automata" ignored="0" name="UpsLoginChromeTest" tests="3" failures="1" timestamp="02 May 2020 22:29:18 GMT" time="27.593" errors="0">
  <testcase name="verifyUpsLoginPageTitle" time="0.025" classname="pack.UpsTest.UpsLoginTest"/>
  <testcase name="verifyLoginButtonText" time="0.062" classname="pack.UpsTest.UpsLoginTest">
    <failure type="java.lang.AssertionError" message="expected [Sign In] but found [Log In]">
      <![CDATA[java.lang.AssertionError: expected [Sign In] but found [Log In]
at pack.UpsTest.UpsLoginTest.verifyLoginButtonText(UpsLoginTest.java:73)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginButtonText -->
  <testcase name="verifyLoginErrorMsg" time="1.522" classname="pack.UpsTest.UpsLoginTest"/>
</testsuite> <!-- UpsLoginChromeTest -->
